enum ActionType {
  addedTextItem,
  addedImageItem,
  addedShapeItem,
  positionItem,
  sizeItem,
  rotationItem,
  changedLayerIndex,
  removedItem,
  draw,
  erase,
  changeTextValue,
  changeImageValue,
  changeShapeValue,
}
